// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: file.proto

package server

import (
	"context"

	"LearningGuide/file_srv/.FileProto"
	"LearningGuide/file_srv/internal/logic"
	"LearningGuide/file_srv/internal/svc"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	__FileProto.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

func (s *FileServer) CreateFile(ctx context.Context, in *__FileProto.CreateFileRequest) (*__FileProto.CreateFileResponse, error) {
	l := logic.NewCreateFileLogic(ctx, s.svcCtx)
	return l.CreateFile(in)
}

func (s *FileServer) GetFileDetail(ctx context.Context, in *__FileProto.FileDetailRequest) (*__FileProto.FileInfoResponse, error) {
	l := logic.NewGetFileDetailLogic(ctx, s.svcCtx)
	return l.GetFileDetail(in)
}

func (s *FileServer) FileList(ctx context.Context, in *__FileProto.FileFilterRequest) (*__FileProto.FileListResponse, error) {
	l := logic.NewFileListLogic(ctx, s.svcCtx)
	return l.FileList(in)
}

func (s *FileServer) UpdateFile(ctx context.Context, in *__FileProto.UpdateFileRequest) (*__FileProto.Empty, error) {
	l := logic.NewUpdateFileLogic(ctx, s.svcCtx)
	return l.UpdateFile(in)
}

func (s *FileServer) DeleteFile(ctx context.Context, in *__FileProto.DeleteFileRequest) (*__FileProto.Empty, error) {
	l := logic.NewDeleteFileLogic(ctx, s.svcCtx)
	return l.DeleteFile(in)
}

func (s *FileServer) CreateSession(ctx context.Context, in *__FileProto.CreateSessionRequest) (*__FileProto.CreateSessionResponse, error) {
	l := logic.NewCreateSessionLogic(ctx, s.svcCtx)
	return l.CreateSession(in)
}

func (s *FileServer) SessionList(ctx context.Context, in *__FileProto.SessionListRequest) (*__FileProto.SessionListResponse, error) {
	l := logic.NewSessionListLogic(ctx, s.svcCtx)
	return l.SessionList(in)
}

func (s *FileServer) DeleteSession(ctx context.Context, in *__FileProto.DeleteSessionRequest) (*__FileProto.Empty, error) {
	l := logic.NewDeleteSessionLogic(ctx, s.svcCtx)
	return l.DeleteSession(in)
}

func (s *FileServer) NewMessage(ctx context.Context, in *__FileProto.NewMessageRequest) (*__FileProto.NewMessageResponse, error) {
	l := logic.NewNewMessageLogic(ctx, s.svcCtx)
	return l.NewMessage(in)
}

func (s *FileServer) MessageList(ctx context.Context, in *__FileProto.MessageListRequest) (*__FileProto.MessageListResponse, error) {
	l := logic.NewMessageListLogic(ctx, s.svcCtx)
	return l.MessageList(in)
}

func (s *FileServer) NewNoun(ctx context.Context, in *__FileProto.NewNounRequest) (*__FileProto.NewNounResponse, error) {
	l := logic.NewNewNounLogic(ctx, s.svcCtx)
	return l.NewNoun(in)
}

func (s *FileServer) NounList(ctx context.Context, in *__FileProto.NounListRequest) (*__FileProto.NounListResponse, error) {
	l := logic.NewNounListLogic(ctx, s.svcCtx)
	return l.NounList(in)
}

func (s *FileServer) GetNounDetail(ctx context.Context, in *__FileProto.NounDetailRequest) (*__FileProto.NounInfoResponse, error) {
	l := logic.NewGetNounDetailLogic(ctx, s.svcCtx)
	return l.GetNounDetail(in)
}

func (s *FileServer) DeleteNoun(ctx context.Context, in *__FileProto.DeleteNounRequest) (*__FileProto.Empty, error) {
	l := logic.NewDeleteNounLogic(ctx, s.svcCtx)
	return l.DeleteNoun(in)
}

func (s *FileServer) NewExercise(ctx context.Context, in *__FileProto.NewExerciseRequest) (*__FileProto.NewExerciseResponse, error) {
	l := logic.NewNewExerciseLogic(ctx, s.svcCtx)
	return l.NewExercise(in)
}

func (s *FileServer) UpdateExercise(ctx context.Context, in *__FileProto.UpdateExerciseRequest) (*__FileProto.Empty, error) {
	l := logic.NewUpdateExerciseLogic(ctx, s.svcCtx)
	return l.UpdateExercise(in)
}

func (s *FileServer) ExerciseList(ctx context.Context, in *__FileProto.ExerciseListRequest) (*__FileProto.ExerciseListResponse, error) {
	l := logic.NewExerciseListLogic(ctx, s.svcCtx)
	return l.ExerciseList(in)
}

func (s *FileServer) GetExerciseDetail(ctx context.Context, in *__FileProto.ExerciseDetailRequest) (*__FileProto.ExerciseInfoResponse, error) {
	l := logic.NewGetExerciseDetailLogic(ctx, s.svcCtx)
	return l.GetExerciseDetail(in)
}

func (s *FileServer) DeleteExercise(ctx context.Context, in *__FileProto.DeleteExerciseRequest) (*__FileProto.Empty, error) {
	l := logic.NewDeleteExerciseLogic(ctx, s.svcCtx)
	return l.DeleteExercise(in)
}

func (s *FileServer) NewSummary(ctx context.Context, in *__FileProto.NewSummaryRequest) (*__FileProto.NewSummaryResponse, error) {
	l := logic.NewNewSummaryLogic(ctx, s.svcCtx)
	return l.NewSummary(in)
}

func (s *FileServer) SummaryList(ctx context.Context, in *__FileProto.SummaryListRequest) (*__FileProto.SummaryListResponse, error) {
	l := logic.NewSummaryListLogic(ctx, s.svcCtx)
	return l.SummaryList(in)
}

func (s *FileServer) GetSummary(ctx context.Context, in *__FileProto.GetSummaryRequest) (*__FileProto.SummaryInfoResponse, error) {
	l := logic.NewGetSummaryLogic(ctx, s.svcCtx)
	return l.GetSummary(in)
}
